name: semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container: 
      image: returntocorp/semgrep
    steps:
    - name: FetchSourceCode
      uses: actions/checkout@v3
    - name: Semgrep Tool
      run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true
    - name: Upload Sarif
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
      if: always()